#!/bin/sh

export QT_STYLE_OVERRIDE="gtk2"

X_USER_RESOURCES=${HOME}/.Xresources
X_USER_MODMAP=${HOME}/.Xmodmap
X_SYS_RESOURCES=/etc/X11/xinit/.Xresources
X_SYS_MODMAP=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f "${X_SYS_RESOURCES}" ]; then
    xrdb -merge "${X_SYS_RESOURCES}"
fi

if [ -f "${X_SYS_MODMAP}" ]; then
    xmodmap "${X_SYS_MODMAP}"
fi

if [ -f "${X_USER_RESOURCES}" ]; then
    xrdb -merge "${X_USER_RESOURCES}"
fi

if [ -f "${X_USER_MODMAP}" ]; then
    xmodmap "${X_USER_MODMAP}"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

exec i3
